### ISSUE TITLE
hello ,my question is , does its safe like when i delete the files and the messages and i turn on the screenshot mode like near it a blue box which is open does its safe still for me ? and does the owners see the messages or files or whatever is? please answer and what is screenshots mode exactly

### ISSUE THREAD

**Issue by andrea1x** [victornpb/undiscord#120]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.
> You may want to use the "Screenshot mode" before taking screenshots or copying logs.

Describe what your question is, try to give as much detail as possible so I can help you.

Post screenshots if applicable.

**Comment by andrea1x** [comment]
I need an answer🖤

**Comment by teisseire117** [comment]
Screenshot mode hides personal informations from the screen so you can take a screenshot and share it without accidently sharing any personal information.
It's not a very important feature but it's here if you want to use it.

**Comment by andrea1x** [comment]
> Screenshot mode hides personal informations from the screen so you can take a screenshot and share it without accidently sharing any personal information.
> 
> It's not a very important feature but it's here if you want to use it.

Thank you for answering me it means alottt🖤🖤🖤🖤🧚🏻‍♀️

**Comment by victornpb** [comment]
"Screenshot mode" is just a mode that it blanks out identifiable information from your screen, so you can take a screenshot without worrying about leaking your identity. It doesn't affect any function other than that.

Indeed. I added this mode because people where posting screenshots of the logs and posting them online.

The log is meant to be seen only by yourself, as it contains your name, massage content, and where and when it was posted.

In order to keep everyone safe I also added a number of warnings like the one you see when you're gonna post stuff here.

```
WARNING: Github Issues are publicly visible, do not post sensitive information here.
You may want to use the "Screenshot mode" before taking screenshots or copying logs.
```

I hope that clear things out a bit. I also suggest you read the pinned issue, where I answer another question about privacy.
