### ISSUE TITLE
[BUG] 404 error when deleting messages with discord's data package

### ISSUE THREAD

**Issue by HugKitten** [victornpb/undiscord#143]
**Describe the bug**
When I try to delete all my messages using my discord data package, it starts and then has the error "Error searching messages, API responded with status 404!" {"message":"404: Not Found", "code: 0"} and none of my messages get deleted.

**To Reproduce**
1) Import your index file
2) Click get on Authorization
3) Click get on Autor
4) Click start
5) 404 error and no deleted messages

**Screenshots / Logs**
![chrome_k7pyoQBEAq](https://user-images.githubusercontent.com/14168321/99185542-5fc20980-26ff-11eb-8475-699481e43c49.png)

**Comment by ZoiAeras** [comment]
I'm having the same issue here. I even tried a different browser just in case it was something weird the Brave was doing. Are the dms with a person you have blocked? That's the case with my dms.

I'm new to anything code so maybe the idea is stupid idk...

It's getting late I might try some different things to figure out what the cause is next week when I have time. Let me know if you've figured it out tho
