### ISSUE TITLE
How to disable the auto delay search. [Question]

### ISSUE THREAD

**Issue by EVilm1** [victornpb/undiscord#155]
Hello,
I use Undiscord via tempermonkey to delete a large amount of messages. (I want to delete more than 10k messages)
The problem is that Discord greatly limits the delay. It's not a surprise but I find it hard to understand.
I start at 1000 delete delay, and 100 search delay. I delete 20 messages perfectly, then after a while the script puts "searching next message" and starts again. The problem is that at this point, it reduces the delay, and after 5 messages I'm limited with a delete delay of 100 000ms...
This is my problem. How to prevent the delay reduction?
I've modified and tested several parameters such as search delay or increasing the delete delay. Without success...
I didn't find a similar problem on the github.
Thanks for your help.

**Comment by AirikWarren** [comment]
I believe Discord has started getting smarter about how they detect scripts like these being run by users and the constant rate of deletion (rather than the delay itself) is what is causing the API limits. 

https://gist.github.com/AirikWarren/12b8a72abf6bf17fe3b9e75d19d60743

I did a really simple fork of the older web developer based console version of the script that randomizes the deletion delay and it seems to have mitigated a lot of the issues. I'm going to have a look over the Undiscord branch and see if I can't incorporate the same change there but for now this should work, albeit a lot more slowly than the original deletion script. 

I'll also have a look at coming up with a more sensible approach to handling increasing the search delay in response to API throttling and finding ways to simulate other API requests that an "authentic" user would be sending the servers that the script doesn't send.
