### ISSUE TITLE
[BUG] browers error frozen?

### ISSUE THREAD

**Issue by AraAraSayonara** [victornpb/undiscord#180]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.
> You may want to use the "Screenshot mode" before taking screenshots or copying logs.

**Describe the bug**
the page doesn't respond and i get a error everytime i deleted anything now i cannot remove any dm.

**To Reproduce**
can't scroll nor click anything and i see a error everythime

**Screenshots / Logs**
If applicable, add screenshots and or copy log to help explain your problem.
![image](https://user-images.githubusercontent.com/79165621/108127882-3624cf80-70ac-11eb-825e-d9a5d04e26ec.png)

```
Paste logs here
cant open the console tab

**Affects** (Add an X to items that apply)
- [ ] DMs
- [ ] DM Groups
- [ ] Channel
- [ ] Channel (NSFW)
- [ ] Server (All Channels)
- [ ] Other (explain)

**System:**
 - OS: [e.g. Windows 10, macOS 10.15.0]
 - Browser [e.g. chrome 69, firefox 42.0]

**Comment by ca-rso-n** [comment]
Clearly you have no idea what you are even doing, I would suggest doing it by hand. And you are probably using a old computer right?

**Comment by rawryourface** [comment]
Late reply but I also stumbled onto an issue where my browsers were timing out (i tried both firefox and chrome to see if it was an issue with one of them) and being unresponsive... 

It seems like if you have someone blocked and start deleting messages in a DM, discord freaks out. I don't think its the script because when I tried to go into the DM where I wanted to delete messages, my discord app froze up as well. Once I unblocked this person the issue went away and the script is working correctly.
