### ISSUE TITLE
[Question] DELETE 0 MESSAGES, 0 FILED

### ISSUE THREAD

**Issue by lillia447** [victornpb/undiscord#195]
It does not allow me to delete messages in a single specific chat, it helps, I get this:  Delete 0 messages, 0 filed. I have tried uninstalling and reinstalling the scripts, even selecting various options in the remover, but nothing.
![descarga - 2021-04-04T114454 922](https://user-images.githubusercontent.com/81922113/113515641-582ec000-953b-11eb-86ec-0b2ac9fbfa41.png)

**Comment by matthewl07** [comment]
Same but idk how 2 fix it.

**Comment by NelsonL97** [comment]
Still no fix for this? having the same issue with 3000+ messages. API returns an empty page...

**Comment by Bloomasaurus** [comment]
Ahoy there I figured out how to fix this. The program doesn't detect the script probably because you have a bunch of call logs so that's the problem. The solution is copy the message link of the last message you want deleted (your newest one). Paste only the numbers into the box labeled "before message with id." 
Get the Authorization, Author and Guild like normal and it should start working. < 3
