### ISSUE TITLE
Discord phone number deleted

### ISSUE THREAD

**Issue by GitTSX** [victornpb/undiscord#203]
After I used the provided method to delete messages I got an email saying 
Your phone number ***********0 was recently removed from this account and added to a different Discord account.

Please note that your phone number can only be linked to one Discord account at a time.

When I try to add my phone number back I get a text back saying an existing discord account is already using this number. Please remove it before it can be used with a new account.

I have no idea what account it went to and i cant add my phone number back to my account

**Comment by Bananaman** [comment]
The script is clean, as explained here:

https://github.com/victornpb/deleteDiscordMessages#about-running-code-on-your-console

I even read through it myself to be sure, and it's clean.

Your phone number issues were caused by something else and is just a coincidence. Has nothing to do with this script, if you installed the clean code from the official places listed on the front page of this project.
