### ISSUE TITLE
[Question] Ended Because API Returned An Empty Page

### ISSUE THREAD

**Issue by SW0L3AT3N** [victornpb/undiscord#228]
![Capture1](https://user-images.githubusercontent.com/87688409/126267214-7e04d90b-6541-4d3c-91a6-f90ba266421c.PNG)

I'll preface this with a warning that I don't know anything about coding. My friend helped me set this up because I wanted to delete some messages with an old friend of mine that I had a major falling out with. In total, I had about 37,000 messages ( our whole chat history ) that I wanted gone and I had the bot on overnight for two nights and got 36,000 of the messages deleted. I had put the last 1,000 off for about two days because I had forgotten and today, when I decided to get it done it said "Ended because API returned an empty page." Whilst acknowledging the 1,000-ish messages still left. Is there something I copy- pasted wrong in the script? Or something else? Thank you so much!

**Comment by jayesha94** [comment]
You can add new messages to the chat, and start again. However, it may show the same message "ended because API returned an empty page" if there is call history in between. So try sending a new message, and deleting by giving date ranges to old messages first, and then delete the new message you just send.
