### ISSUE TITLE
Token field being miss detected as a password/login form by browser/password manager

### ISSUE THREAD

**Issue by Jonizz** [victornpb/undiscord#232]
### **Alright so after using this I pressed the trashcan to close out of the "menu" but then I got hit with a notification from chrome if I wanted to save my new password? Nice try!**

**Comment by Toby222** [comment]
That's because the token input field is a password field.
Chrome/Chromium (and probably other) browsers have a password manager that allows you to save passwords written into these fields, along with an optional username/email

Your browser was just asking if it should store the input to that field, like it does with any other.

The HTML of the input field, showing its input type
![image](https://user-images.githubusercontent.com/14962962/127160611-f73cf328-0a7e-4042-855b-d83ecb3be24d.png)

Brave showing password-relevant menu entries
![image](https://user-images.githubusercontent.com/14962962/127160433-3a4bf139-e2f3-4157-be5d-99d4729eb691.png)

Brave recommending my actual Discord password for the token field
![image](https://user-images.githubusercontent.com/14962962/127160718-35447293-71be-43d0-a565-08e54d7feba2.png)

Brave offering a change to my password after typing something into the token field
![image](https://user-images.githubusercontent.com/14962962/127161251-46a5464d-8171-4ae6-bc4f-a4a7eb26638e.png)

**Comment by victornpb** [comment]
I've used a password field for the token instead of a plain text field so people don't accidentally take screenshots of their tokens. I've put number of safety measure to ensure that doesn't happen:

- **Screenshot mode**, which redacts all private information from the screen, turning every field in password fields, and I encourage people to  use it, like here, this is the template you see when opening an issue:
    ![image](https://user-images.githubusercontent.com/3372598/128605659-d3769812-edec-40ec-b9be-81fc13e145f6.png)
- Warnings like this:
  [https://github.com/victornpb/deleteDiscordMessages#do-not-share-your-authtoken](https://github.com/victornpb/deleteDiscordMessages#do-not-share-your-authtoken)

The token field is so sensible that I chose to make it permanently cloaked.
As explained by @Toby222, password managers and browsers may think this password field is a login form. I could circumvent this **false positive** by not even putting the token in a field, but this tool started as a full manual tool, then I added the helper buttons to make filling the variables easier, but it still can be used even if the "get" auto detection can't fill it automatically.

I also encourage people to audit the code that is present inside your browser extension, example: 
![image](https://user-images.githubusercontent.com/3372598/128606212-d97b3a48-d416-45ed-8375-4cbf302b7912.png)
You will be able to see that there are no external dependencies, there are no tracking scripts or pixels, nothing is loaded externally nor sent to anywhere other than discord delete and discord search api.

I hope that clears things up

I'm also open to feedback, if removing the token textfield completely reduces confusion like this, I’m willing to remove it. Even tho this is the first time I see this happen.
