### ISSUE TITLE
Can't Delete Messages Anymore[Question] 

### ISSUE THREAD

**Issue by bunnyyx** [victornpb/undiscord#256]
Using Version 2.9.3 (x64)in Chrome

All of a sudden it's not deleting my messages and I can't figure out why
![discord](https://user-images.githubusercontent.com/74756547/134152445-f0aa9e88-37ac-421b-b9cf-0bb815f11df1.png)

**Comment by bunnyyx** [comment]
![Uploading discord.png…]()

**Comment by itsandreramon** [comment]
same issue

**Comment by aurae-dc** [comment]
having the same issue

**Comment by bottlesandeggs** [comment]
Having the same issue. Worked fine as early as last night.

**Comment by Ten2O** [comment]
Same issue, was working then randomly stopped. Now it just says this.

**Comment by d0wn2** [comment]
Same issue.So far i have confirmed it affects Ubuntu and Windows, both with Firefox. Seems to be hitting a Discord ratelimit or something.

**Comment by FusionDragon** [comment]
> Same issue.So far i have confirmed it affects Ubuntu and Windows, both with Firefox. Seems to be hitting a Discord ratelimit or something.

This is an issue (I assume) caused by the way discord loads messages in pages, you can solve this by going to your search bar and typing "from:" then select your username. Find the last message you sent and take the ID of the message after that, then put that ID into the "Before a message" field under "INTERVAL OF MESSAGES" and click start.

**Comment by pantsmode** [comment]
Could also be about Discord not allowing you to delete messages that are beyond 14 days old.

**Comment by FusionDragon** [comment]
I think that's just specifically for bots. I've never had an issue with older messages.
