### ISSUE TITLE
I want to request additional features.

### ISSUE THREAD

**Issue by GitHubkaede** [victornpb/undiscord#259]
situation:

I delete the message, but the BOT of the server will still collect (record) my original message.

So I wonder if there is a function,

"Batch edit messages, for example, I set the value to 1234, then when I delete the message, when the BOT collects the message, it will be 1234.

Although it may not be a good suggestion, maybe someday this suggestion can be adopted.

(I use Google translate.)

**Comment by SethFalco** [comment]
To be fair, I think this is a nice suggestion.
Where I can, I often edit my message/post/comment with `{REDACTED}` first, then delete it.

I doubt it makes much of a difference in most cases since most platforms likely store all versions of the message, but it can be nice for the paranoid people. (including me)
