### ISSUE TITLE
[BUG] rate limited

### ISSUE THREAD

**Issue by Jasey678** [victornpb/undiscord#411]
![image](https://user-images.githubusercontent.com/114431574/192340661-149c22ab-e98c-430c-b721-435abcde2505.png)

keep getting this popping up every 5 seconds while it's deleting messages and I don't know what to do. This never used to happen before last time I used it. I tried changing the "search" and "delete" delays and it still continues happening.

**Comment by biast12** [comment]
Discord is rate limiting you, it's not a bug or anything like that, it's because you're sending too many requests when you delete messages

**Comment by biast12** [comment]
you don't, it's there to prevent people Ddosing Discords servers

**Comment by Jasey678** [comment]
Bruh, this never happened before though when i first started using it 😭 but ok then

**Comment by abbydiode** [comment]
Discord has increased how strict their cooldowns are over the recent years so it is indeed possible that you used to be able to delete faster.

I would recommend setting the delete delay in the advanced section to 2500 ms. The current default is out of date.

**Comment by Jasey678** [comment]
> Discord has made rate limiting a lot stricter in recent years, so it is indeed possible that you used to be able to delete faster.
> 
> I would recommend setting the delete delay in the advanced section to 2500 ms. The current default is out of date, see https://github.com/victornpb/undiscord/wiki/delay and #402.

Oh ok thanks for the help I see if this would make it work better so it doesn't pause on the rate limited message for too long.

**Comment by ofernandofilo** [comment]
as already said, it's not a bug, it's expected behavior and determined by the discord server.

in personal tests, for you it may be different, I arrived at the values, as the lowest values, [search delay: 6400] and [delete delay: 2000] when deleting more than 500 messages at once. 

any value below displays the message "being rate limited by the API".

for a smaller number of deleted messages, lower values can be used. however, with these values I delete more than 10K without any API mishap. [40K+ at the moment... and it will take more than 1 day.] _o/
