### ISSUE TITLE
[Question] Does this work for a server I've been banned from?

### ISSUE THREAD

**Issue by ZeldaPlayer29** [victornpb/undiscord#98]
I used to be in a really toxic Discord server that banned me for asking them to be more respectful towards me. I decided I don't want any of my messages in that server any more and was hoping I could use this to delete them all. However, it's giving me a 403 access error when I fill in the details (I got the server/channel IDs from Discord's data download option). Is there anything that can be done?

**Comment by victornpb** [comment]
You can't delete a message unless you know the guildId, the only exception is for DMs which doesn't have a Guild.
About the servers you are banned I don't know, I'd assume you will get a non authorized error, but you can test this by creating a server, grab the ids, leave it and click start

**Comment by Bruk749** [comment]
I have the same problem, helped a server for months and they ditched and all the info I had in the server is still there, I would love to delete it.

**Comment by ZeldaPlayer29** [comment]
Sadly I don't think it can be done due to authorisation. I retrieved the guildID, as well as each separate channelID, by downloading my Discord data but it responses with an error message, I think because when you are banned from a server you lose authorisation to do anything in that server. But you can still try it with your server if you go to Discord settings and choose to download your data, which will allow you to retrieve the IDs.

**Comment by victornpb** [comment]
I’m not an expert on the subject, but I think if you terminate your account you can request to have all your data wiped, and I think discord is compliant with the new laws regarding data protection and the right to be forbidden. If you really want that I think it worth trying to get an answer from discord support. Let us know if you they get back to you

**Comment by Bruk749** [comment]
Thanks I will try that I've been contacting Discord about this too. Next time they reply I'm gonna ask if terminating my account can wipe all my info. However in some servers I've seen messages that say 'Deleted User'.

**Comment by mattsyl** [comment]
AFAIK deleting your Discord data with the big shiny delete account button doesn't delete your messages with others or in guilds -- it just changes your username to "Deleted user XXXXXXX" and removes some data such as your email and phone number, profile picture, connected accounts etc. Their help pages aren't very helpful, but this is what I've seen in practice.

**Comment by Bruk749** [comment]
So how do you terminate the account then?

**Comment by ZeldaPlayer29** [comment]
I think you need to delete it with the delete account button and contact Discord Support with your account details and ask them to remove the data. Otherwise if you don't request it your messages stay with the label "Deleted User".

In my case, I don't want to lose my account and all my messages, I just wanted the ones sent to the nasty server deleted. I did try contacting Discord Support about this with my details and they told me they won't interfere and delete any messages unless there is a breach in their TOS which in my case there is not. They said I'd just have to ask the server owner to unban me which is never gonna happen.

**Comment by mattsyl** [comment]
@ZeldaPlayer29 If Discord Support refused to remove your messages without a TOS breach, why would you suggest that @Bruk749 contact Discord Support asking that same thing? Are you trying to say that it is more of an "all or nothing" deal where they'll only remove selective messages with a TOS breach, otherwise you can only ask for all of your messages in all of your guilds to be deleted?

**Comment by victornpb** [comment]
My assumption was based on this https://en.m.wikipedia.org/wiki/Right_to_be_forgotten

But again I don’t understand the legal nuances, but I think this would only be valid for a full account wipe, bc from a practical point they will probably not selectively delete stuff.

**Comment by mattsyl** [comment]
Based on the assumption that they don't delete messages when an account is deleted I'm willing to bet their interpretation of RtbF considers sent messages to be exempt, because there is wiggle room in current GDPR/Privacy Shield compliang regs for certain types of data to be exempt when RtbF is invoked. I believe the wording is along the lines of "necessary for the continued function of the service" and there is a case to be made that preserving messages people have made in guilds fits that description. Can't hurt to send them an email if you're curious.

You are correct in saying that you can't selectively invoke RtbF. If there is some specific piece of personal data that you can't otherwise delete that invoking RtbF would get rid of, that's your only option.

**Comment by ZeldaPlayer29** [comment]
One thought I've just had is that you could ask the server owner (or a server admin) to use this tool to delete all your messages for you. It's not really ideal but, in my case, I'm not sure what else to do.

**Comment by Bruk749** [comment]
Yea, the admin is more or less my friend is letting me delete my comments, however now I found another problem some of my messages that include photos don't go away, while I was deleting my comments I saw this also some messages don't get deleted as well.

**Comment by ZeldaPlayer29** [comment]
Well, I've emailed the guy and asked him to do it for me, although I'm not sure he will. I kinda didn't want to do it because they were making fun of me for deleting some previous messages I had sent, but I don't want to be associated with the server at all now so I don't really have much of choice.

**Comment by ZeldaPlayer29** [comment]
Sigh, knew it wouldn't work

**Comment by mattsyl** [comment]
I contacted Discord support to ask about their policy on removing messages when an account is deleted. I'll update as soon as I get a response.

@ZeldaPlayer29 If, when Discord responds to me, it turns out that Discord does allow users who delete their accounts some option to have their entire message history removed, even across guilds which they may no longer have access to, I'd advise you to take this option, as it appears to be your only one to get those messages removed. It's not hard to transfer guild ownership, friends lists, and if you want your PM message history saved, you can request a data download. If you have Nitro, you might have some sentimental value attached to the date on the badge on your profile, but if that's worth more to you than having those messages deleted then you probably wouldn't have commented here. Beyond, say, creating an alternate account, joining that Discord server and over a period of time attaining their trust enough for them to give you the "manage messages" permission, you don't have any other options.

@Bruk749 I'm not sure what you mean. Any picture sent on Discord is the same object as a message and can be deleted the same way. The only messages which can't be deleted w/o "manage messages" are system messages, i.e. joining/boosting a server. Are you referring to reactions, or messages sent by bots which contain pictures, or the server picture, or something else?
